-- Create a date dimension table
-- CREATE OR REPLACE TABLE date_dimension AS
WITH RECURSIVE date_range AS (
  SELECT DATE('1970-01-01') AS DATA -- Start date
  UNION ALL
  SELECT DATEADD(DAY, 1, DATA)
  FROM date_range
  WHERE DATA < DATE('2050-12-31') -- End date
)
SELECT
  DATA,
  YEAR(DATA) AS ANO,
  MONTH(DATA) AS MES,
  DAY(DATA) AS DIA,
  CASE
    WHEN MONTH(DATA) = 1 THEN 'Janeiro'
    WHEN MONTH(DATA) = 2 THEN 'Fevereiro'
    WHEN MONTH(DATA) = 3 THEN 'Março'
    WHEN MONTH(DATA) = 4 THEN 'Abril'
    WHEN MONTH(DATA) = 5 THEN 'Maio'
    WHEN MONTH(DATA) = 6 THEN 'Junho'
    WHEN MONTH(DATA) = 7 THEN 'Julho'
    WHEN MONTH(DATA) = 8 THEN 'Agosto'
    WHEN MONTH(DATA) = 9 THEN 'Setembro'
    WHEN MONTH(DATA) = 10 THEN 'Outubro'
    WHEN MONTH(DATA) = 11 THEN 'Novembro'
    WHEN MONTH(DATA) = 12 THEN 'Dezembro'
  END AS DESC_MES,
  CEIL(MONTH(DATA) / 3) AS TRIMESTRE,
  CONCAT(CEIL(MONTH(DATA) / 3), 'o Trimestre') AS DESC_TRIMESTRE,
  CEIL(MONTH(DATA) / 4) AS QUADRIMESTRE,
  CONCAT(CEIL(MONTH(DATA) / 4), 'o Quadrimestre') AS DESC_QUADRIMESTRE,
  CASE WHEN MONTH(DATA) <= 6 THEN 1 ELSE 2 END AS SEMESTRE,
  CASE WHEN MONTH(DATA) <= 6 THEN '1o Semestre' ELSE '2o Semestre' END AS DESC_SEMESTRE,
  EXTRACT(DOW FROM DATA) + 1 AS DIA_SEMANA,
  CASE
    WHEN EXTRACT(DOW FROM DATA) = 0 THEN 'Domingo'
    WHEN EXTRACT(DOW FROM DATA) = 1 THEN 'Segunda-feira'
    WHEN EXTRACT(DOW FROM DATA) = 2 THEN 'Terça-feira'
    WHEN EXTRACT(DOW FROM DATA) = 3 THEN 'Quarta-feira'
    WHEN EXTRACT(DOW FROM DATA) = 4 THEN 'Quinta-feira'
    WHEN EXTRACT(DOW FROM DATA) = 5 THEN 'Sexta-feira'
    WHEN EXTRACT(DOW FROM DATA) = 6 THEN 'Sábado'
  END AS DESC_DIA_SEMANA,
  CEIL(DAY(DATA) / 7) AS SEMANA_MES,
  CONCAT(CEIL(DAY(DATA) / 7), 'a Semana') AS DESC_SEMANA,
  TO_NUMBER(TO_CHAR(DATA, 'YYYYMM')) AS ANO_MES,
  TO_CHAR(DATA, 'MM-YYYY') AS MES_ANO,
  CASE
    WHEN MONTH(DATA) = 1 THEN 'JAN'
    WHEN MONTH(DATA) = 2 THEN 'FEV'
    WHEN MONTH(DATA) = 3 THEN 'MAR'
    WHEN MONTH(DATA) = 4 THEN 'ABR'
    WHEN MONTH(DATA) = 5 THEN 'MAI'
    WHEN MONTH(DATA) = 6 THEN 'JUN'
    WHEN MONTH(DATA) = 7 THEN 'JUL'
    WHEN MONTH(DATA) = 8 THEN 'AGO'
    WHEN MONTH(DATA) = 9 THEN 'SET'
    WHEN MONTH(DATA) = 10 THEN 'OUT'
    WHEN MONTH(DATA) = 11 THEN 'NOV'
    WHEN MONTH(DATA) = 12 THEN 'DEZ'
  END AS DESC_MES_ABREV,
  EXTRACT(DOW FROM DATA) + 1 AS NUM_DIA_SEMANA_ORD,
  CONCAT(EXTRACT(DOW FROM DATA) + 1, 'o Dia') AS DESC_DIA_SEMANA_ORD,
  WEEK(DATA) AS NUM_SEMANA,
  -- TO_NUMBER(TO_CHAR(DATA, 'YYYYWW')) AS NUM_ANO_SEMANA,
  DATEADD(DAY, -EXTRACT(DOW FROM DATA), DATA) AS DATA_INICIO_SEMANA_DOM,
  DATEADD(DAY, CASE WHEN EXTRACT(DOW FROM DATA) = 0 THEN -6 ELSE 1 - EXTRACT(DOW FROM DATA) END, DATA) AS DATA_INICIO_SEMANA_SEG,
  DATE_TRUNC('MONTH', DATA) AS DATA_INICIO_MES,
  DATE_TRUNC('YEAR', DATA) AS DATA_INICIO_ANO
FROM date_range;
